name: "ghcr.io Container Cleanup"

description: 'A GitHub Action that cleans up old ghcr.io Containers'

branding:
    icon: 'package'
    color: 'orange'

inputs:
    # Global (for all steps)
    token:
        description: 'A github token with the read:packages, write:packages and delete:packages permissions'
        required: true
    package:
        description: 'Name of the package (e.g. for "ghcr.io/example/container" the packageName is "container")'
        required: true
    owner:
        description: 'The owner of the package (for regular users this value is always "user" and NOT your name, for organizations this value is "orgs/<Name of Org>")'
        required: true

    # Delete images
    delete_tagged:
        description: 'Delete all TAGGED containers (1/0)'
        required: false
        default: '1'
    keep_versions:
        description: 'The minimum amount of versions to keep'
        required: false
        default: '30'
    minimum_days:
        description: 'The minimum age (in days) that an image has to be untouched'
        required: false
        default: '14'
    skip_tags:
        description: 'A comma separated list of Tags that should be skipped'
        required: false
        default: 'latest'

    # Delete untagged images
    delete_untagged:
        description: 'Delete all untagged containers (1/0)'
        required: false
        default: '0'
    keep_versions_untagged:
        description: 'The minimum amount of untagged versions to keep'
        required: false
        default: '14'

runs:
    using: composite
    steps:
        -   name: "Checkout the davahome/ghcr-cleanup repo to access scripts"
            uses: actions/checkout@v3
            with:
                repository: "davahome/ghcr-cleanup"
                path: "ghcr-cleanup"
                ref: "v1.1"

        -   name: 'Delete untagged images from ghcr.io'
            uses: actions/github-script@v7
            if: inputs.delete_untagged != '0'
            with:
                github-token: '${{ inputs.token }}'
                script: |
                    const path = require('path');
                    const scriptPath = path.resolve('./ghcr-cleanup/src/delete-untagged.js');
                    
                    const input = ${{ toJson(inputs) }};
                    
                    await require(scriptPath)({github, input});


        -   name: 'Delete images from ghcr.io'
            uses: actions/github-script@v7
            if: inputs.delete_tagged != '0'
            with:
                github-token: '${{ inputs.token }}'
                script: |
                    const path = require('path');
                    const scriptPath = path.resolve('./ghcr-cleanup/src/delete.js');
                    
                    const input = ${{ toJson(inputs) }};
                    
                    await require(scriptPath)({github, input});
