action: actions/github-script@v3
scripts:
    -   name: Delete untagged images from ghcr.io
        path: scripts/delete-untagged.js
    -   name: Delete images from ghcr.io
        path: scripts/delete.js

